/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dht_proto_constants.h"

namespace proto { namespace dht {

const dht_protoConstants g_dht_proto_constants;

dht_protoConstants::dht_protoConstants() {
  PROTOCOL_MAGIC = 213;

  PROTOCOL_VERSION = 1;

}

}} // namespace

