/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dht_proto_CONSTANTS_H
#define dht_proto_CONSTANTS_H

#include "dht_proto_types.h"

namespace proto { namespace dht {

class dht_protoConstants {
 public:
  dht_protoConstants();

  int8_t PROTOCOL_MAGIC;
  int8_t PROTOCOL_VERSION;
};

extern const dht_protoConstants g_dht_proto_constants;

}} // namespace

#endif
